# Generated by Django 2.1.15 on 2020-07-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address_2',
        ),
    ]
